version: "3.3"
services:
    mongo:
        image: mongo
        restart: always
        ports:
            - 27017:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: fran
            MONGO_INITDB_ROOT_PASSWORD: pass123

    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: fran
            ME_CONFIG_MONGODB_ADMINPASSWORD: pass123
